### ISSUE TITLE
Update search bar to have a dynamic output 

### ISSUE THREAD

**Issue by AlexandreGazagnes** [NidalChateur/OC_P12_EPIC_EVENTS#1]
Use case : if I start to write 1ST 3 letters of a client, I wand an update of the search bar 
=> specific endpoint
=> use jquery 
=> FORBIDDEN to push this feature BEFORE client demo (due date 2024-01-15)

**Comment by NidalChateur** [comment]
ok let's do it in the next sprint

**Comment by NidalChateur** [comment]
ok non prioritaire
