### ISSUE TITLE
Add click Support 

### ISSUE THREAD

**Issue by AlexandreGazagnes** [NidalChateur/OC_P12_EPIC_EVENTS#3]
https://click.palletsprojects.com/en/8.1.x/

**Comment by NidalChateur** [comment]
J’etais en train de bosser en parallèle de P13 l’interface en ligne de commande jusqu’a ce que je recois un mail qui m’annonce la validation du projet 😄

**Comment by NidalChateur** [comment]
Project recreated using a CLI interface here : https://github.com/NidalChateur/OC_P12_EPIC_EVENTS_CLI.

Thanks for your contribution and your help.
